apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openeo-workspaces-api.fullname" . }}-config
  labels:
    {{- include "openeo-workspaces-api.labels" . | nindent 4 }}
data:
  DEBUG: "{{ .Values.config.debug }}"
  API_VERSION: "{{ .Values.config.apiVersion }}"
  DEFAULT_WORKSPACE_PROVIDER: "{{ .Values.config.defaultWorkspaceProvider }}"
  MAX_WORKSPACE_QUOTA: "{{ .Values.config.maxWorkspaceQuota }}"
  SUPPORTED_PROVIDERS: {{ toJson .Values.config.supportedProviders }}

  OIDC_ISSUER_URL: "{{ .Values.oidc.issuerUrl }}"
  OIDC_CLIENT_ID: "{{ .Values.oidc.clientId }}"
  OIDC_VERIFY_TLS: "{{ .Values.oidc.verifyTls }}"
  OIDC_VERIFY_AUDIENCE: "{{ .Values.oidc.verifyAudience }}"

  GIT_REPO_PATH: "{{ .Values.git.repoPath }}"
  GIT_REMOTE_URL: "{{ .Values.git.remoteUrl }}"
  GIT_AUTHOR_NAME: "{{ .Values.git.authorName }}"
  GIT_AUTHOR_EMAIL: "{{ .Values.git.authorEmail }}"

