apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openeo-workspaces-api.fullname" . }}-secrets
  labels:
    {{- include "openeo-workspaces-api.labels" . | nindent 4 }}
type: Opaque
data:
  oidc_client_secret: {{ .Values.oidc.clientSecret | b64enc | quote }}

  {{- if .Values.elasticsearch.external.enabled }}
  elasticsearch_password: {{ .Values.elasticsearch.external.password | b64enc | quote }}
  {{- else if .Values.elasticsearch.enabled }}
  elasticsearch_password: {{ "" | b64enc | quote }}
  {{- end }}

